- name: Define MediaMTX version
  set_fact:
    mediamtx_version: "v1.13.0"

- name: Install dependencies
  package:
    name:
      - curl
      - tar
    state: present

- name: Download MediaMTX from GitHub
  get_url:
    url: "https://github.com/bluenviron/mediamtx/releases/download/{{ mediamtx_version }}/mediamtx_{{ mediamtx_version }}_linux_amd64.tar.gz"
    dest: /tmp/mediamtx.tar.gz
    mode: '0644'

- name: Extract MediaMTX
  unarchive:
    src: /tmp/mediamtx.tar.gz
    dest: /usr/local/bin/
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Ensure executable
  file:
    path: /usr/local/bin/mediamtx
    mode: '0755'

- name: Create config directory
  file:
    path: /etc/mediamtx
    state: directory
    mode: '0755'

- name: Deploy config file
  template:
    src: mediamtx.yml.j2
    dest: /etc/mediamtx/mediamtx.yml
    mode: '0644'

- name: Create systemd service
  copy:
    dest: /etc/systemd/system/mediamtx.service
    content: |
      [Unit]
      Description=MediaMTX (RTSP Server)
      After=network.target

      [Service]
      ExecStart=/usr/local/bin/mediamtx /etc/mediamtx/mediamtx.yml
      Restart=always
      User=root

      [Install]
      WantedBy=multi-user.target
    mode: '0644'

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Enable and start MediaMTX
  systemd:
    name: mediamtx
    enabled: yes
    state: started

- name: awscliをインストール
  package:
    name: awscli
    state: present

- name: S3から動画ファイルをダウンロード
  command: >
    aws s3 cp s3://{{ s3_bucket }}/video/sample.mp4 /opt/sample.mp4
  args:
    creates: /opt/sample.mp4

- name: ffmpeg systemdサービスユニットを設置
  copy:
    dest: /etc/systemd/system/ffmpeg-rtsp.service
    content: |
      [Unit]
      Description=FFmpeg RTSP Stream
      After=network.target mediamtx.service

      [Service]
      ExecStart=/usr/bin/ffmpeg -re -stream_loop -1 -i /opt/sample.mp4 -c copy -f rtsp rtsp://localhost:8554/stream
      Restart=always
      RestartSec=3

      [Install]
      WantedBy=multi-user.target

- name: ffmpegサービスを有効化・起動
  systemd:
    name: ffmpeg-rtsp
    enabled: yes
    state: started
