name: Deploy to dev environment (Using GitHub OIDC for AWS Auth)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure AWS credentials via OIDC
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.OIDC_ROLE_ARN_GITHUB }}
        aws-region: ap-northeast-1

    - name: Get Bastion Public IP
      id: get_ip
      run: |
        BASTION_IP=$(aws ec2 describe-instances \
          --filters "Name=tag:Name,Values=bastion_ansible" "Name=instance-state-name,Values=running" \
          --query "Reservations[0].Instances[0].PublicIpAddress" \
          --output text)

        echo "bastion_ip=$BASTION_IP" >> "$GITHUB_OUTPUT"

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.BASTION_SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519

    - name: Copy Ansible files to bastion
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./ansible/ \
          ${{ secrets.BASTION_USER }}@${{ steps.get_ip.outputs.bastion_ip }}:~/ansible/

    - name: Run Ansible playbook on bastion
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.BASTION_USER }}@${{ steps.get_ip.outputs.bastion_ip }} \
          "cd ~/ansible && ansible-playbook -i inventory playbook.yml"
